version: '2.1'
services:
  schedule:
    container_name: schedule_api
    image: ulexus/meteor
    ports:
     - "1111:1111"
    links:
     - mongo
     - mysql
    volumes:
      - ./:/usr/src/schedule/
    environment:
     - REPO=https://github.com/Differential/meteor-boilerplate
     - ROOT_URL=http://192.168.59.103
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  mysql:
    container_name: schedule_mysql
    image: mysql:5.7
    ports:
      - '33064:33064'
    command: |
      mysqld
      --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
      --character-set-server=utf8
      --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=schedule
    healthcheck:
      test: mysql --password=${DB_PASS} -e "SELECT 1" schedule
      retries: 3
      interval: 15s
    volumes:
      - ./etc/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf


